name: spark_navigator
description: Smart companion for Spark delivery drivers
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1^.1.0
  http: ^2^.1.0
  cupertino_icons: ^2^.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
